export const DISTRACTIONS = [
  "Go to your front door and count how many TV aerials you can see",
  "Sharpen every pencil you own",
  "Eat a piece of fruit — slowly, no rushing",
  "Make yourself a cup of tea or coffee",
  "Do 10 slow shoulder rolls, then 10 the other way",
  "Find 5 things in the room that are the same colour",
  "Look out of the nearest window and count how many moving things you can see",
  "Refill your water bottle or glass",
  "Write your name in your neatest handwriting 5 times",
  "Sort the pens and pencils on your desk by colour",
  "Do 10 star jumps",
  "Fold a piece of paper into the best paper aeroplane you can manage",
  "Find something that smells nice and just smell it for a bit",
  "Do a slow lap of the room you're in",
  "Stack something — coins, books, boxes — as high as it'll go",
  "Close your eyes and try to identify 5 different sounds you can hear",
  "Doodle something — anything — on a scrap of paper",
  "Count the number of words on the nearest product packaging",
  "Rearrange something on your desk until it looks exactly right",
  "Do a very slow stretch: arms up, bend left, bend right, touch toes",
  "Find the oldest thing in the room",
  "Look up one random Wikipedia article and read just the intro",
  "Tidy up the cables on your desk",
  "Write a 3-word summary of how you're feeling right now",
  "Find 3 things that are slightly out of place and put them back",
  "Do 10 slow neck rolls",
  "Make your chair as comfortable as possible — adjust everything",
  "Write a haiku about your current surroundings (5-7-5 syllables)",
  "Count all the right angles you can see from where you're sitting",
  "Do 10 calf raises standing at your desk",
  "Tear a piece of paper into the smallest pieces you can",
  "Arrange your bookmarks or tabs into some kind of order",
  "Try to balance a pen on your upper lip",
  "Go and look at the sky for 2 minutes",
  "Find something dusty and wipe it clean",
  "Write a very short list of 3 things you're looking forward to",
  "Do a quick lap of the outside of the building",
  "Pick up any rubbish on your desk and bin it",
  "See how long you can balance on one foot",
  "Look at a clock and watch the seconds hand for exactly one minute",
  "Send a nice message to someone you haven't spoken to in a while",
  "Rearrange the icons on your phone's home screen",
  "Find something broken and decide if it's worth fixing",
  "Water any nearby plants",
  "Stand in the doorway and stretch your arms across the frame",
  "Count the number of steps between your desk and the front door",
  "Write down three things you've achieved this week, however small",
  "Find something you own that you've forgotten about",
  "Close every app you're not using right now",
  "Organise your wallet, bag or pockets",
  "Do 5 slow, deep breaths — 4 counts in, hold 4, out 6",
  "Look at your hands and really look at them for 30 seconds",
  "Go get a snack — but eat it away from your desk",
  "Put on one song and do absolutely nothing else while it plays",
  "Find something in the room that makes you smile",
  "Write the alphabet backwards as fast as you can",
  "Do 10 slow wrist circles each direction",
  "Tidy one drawer — just one",
  "Count the number of books you own with red spines",
  "Find something with an interesting texture and feel it properly",
  "Step outside and take 5 slow breaths of fresh air",
  "Do 10 wall push-ups",
  "Look at the ceiling and find a shape in any marks or patterns",
  "Write down one thing you're worried about, then fold the paper away",
  "Find the quietest spot in the building and stand there for 2 minutes",
  "Count every light source you can see",
  "Stretch your fingers out as wide as they'll go and hold for 10 seconds",
  "Move something heavy from one place to another",
  "Find an interesting word in any book and look up its origin",
  "Make a small origami shape — even just a simple box",
  "Do a lap of the room picking up anything that doesn't belong there",
  "Think of 5 animals beginning with the letter S",
  "Go and look in the mirror — say something encouraging to yourself",
  "Find your oldest piece of tech and have a look at it",
]
